################################################################################
# Automatically-generated file. Do not edit!
################################################################################

I_SRCS := 
S_SRCS := 
ASM_UPPER_SRCS := 
CPCP_SRCS := 
ASM_SRCS := 
C_SRCS := 
MCS_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
I_DEPS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 
CPCP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
0_Src/AppSw/CpuGeneric/Config \
0_Src/AppSw/Tricore/Cfg_Ssw \
0_Src/AppSw/Tricore/Main \
0_Src/AppSw/Tricore/rt-thread/libcpu \
0_Src/AppSw/Tricore/rt-thread/src \
0_Src/BaseSw/Ethernet/Phy_Dp83825i \
0_Src/BaseSw/Ethernet/lwip/port/src \
0_Src/BaseSw/Ethernet/lwip/src/api \
0_Src/BaseSw/Ethernet/lwip/src/core \
0_Src/BaseSw/Ethernet/lwip/src/core/ipv4 \
0_Src/BaseSw/Ethernet/lwip/src/core/ipv6 \
0_Src/BaseSw/Ethernet/lwip/src/netif \
0_Src/BaseSw/Ethernet/lwip/src/netif/ppp \
0_Src/BaseSw/Ethernet/lwip/src/netif/ppp/polarssl \
0_Src/BaseSw/Infra/Platform/Tricore/Compilers \
0_Src/BaseSw/Infra/Ssw/TC37A/Tricore \
0_Src/BaseSw/Service/CpuGeneric/If \
0_Src/BaseSw/Service/CpuGeneric/StdIf \
0_Src/BaseSw/Service/CpuGeneric/SysSe/Bsp \
0_Src/BaseSw/Service/CpuGeneric/SysSe/Comm \
0_Src/BaseSw/Service/CpuGeneric/SysSe/General \
0_Src/BaseSw/Service/CpuGeneric/SysSe/Math \
0_Src/BaseSw/Service/CpuGeneric/SysSe/Time \
0_Src/BaseSw/UART \
0_Src/BaseSw/iLLD/TC37A/Tricore/Asclin/Asc \
0_Src/BaseSw/iLLD/TC37A/Tricore/Asclin/Lin \
0_Src/BaseSw/iLLD/TC37A/Tricore/Asclin/Spi \
0_Src/BaseSw/iLLD/TC37A/Tricore/Asclin/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Can/Can \
0_Src/BaseSw/iLLD/TC37A/Tricore/Can/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Ccu6/Icu \
0_Src/BaseSw/iLLD/TC37A/Tricore/Ccu6/PwmBc \
0_Src/BaseSw/iLLD/TC37A/Tricore/Ccu6/PwmHl \
0_Src/BaseSw/iLLD/TC37A/Tricore/Ccu6/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Ccu6/TPwm \
0_Src/BaseSw/iLLD/TC37A/Tricore/Ccu6/Timer \
0_Src/BaseSw/iLLD/TC37A/Tricore/Ccu6/TimerWithTrigger \
0_Src/BaseSw/iLLD/TC37A/Tricore/Convctrl/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Cpu/Irq \
0_Src/BaseSw/iLLD/TC37A/Tricore/Cpu/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Cpu/Trap \
0_Src/BaseSw/iLLD/TC37A/Tricore/Dma/Dma \
0_Src/BaseSw/iLLD/TC37A/Tricore/Dma/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Dts/Dts \
0_Src/BaseSw/iLLD/TC37A/Tricore/Dts/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Edsadc/Edsadc \
0_Src/BaseSw/iLLD/TC37A/Tricore/Edsadc/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Eray/Eray \
0_Src/BaseSw/iLLD/TC37A/Tricore/Eray/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Evadc/Adc \
0_Src/BaseSw/iLLD/TC37A/Tricore/Evadc/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Fce/Crc \
0_Src/BaseSw/iLLD/TC37A/Tricore/Fce/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Flash/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Geth/Eth \
0_Src/BaseSw/iLLD/TC37A/Tricore/Geth/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gpt12/IncrEnc \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gpt12/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Atom/Dtm_PwmHl \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Atom/Pwm \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Atom/PwmHl \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Atom/Timer \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Tim/In \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Tim/Timer \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Tom/Dtm_PwmHl \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Tom/Pwm \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Tom/PwmHl \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Tom/Timer \
0_Src/BaseSw/iLLD/TC37A/Tricore/Gtm/Trig \
0_Src/BaseSw/iLLD/TC37A/Tricore/Hssl/Hssl \
0_Src/BaseSw/iLLD/TC37A/Tricore/Hssl/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/I2c/I2c \
0_Src/BaseSw/iLLD/TC37A/Tricore/I2c/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Iom/Driver \
0_Src/BaseSw/iLLD/TC37A/Tricore/Iom/Iom \
0_Src/BaseSw/iLLD/TC37A/Tricore/Iom/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Msc/Msc \
0_Src/BaseSw/iLLD/TC37A/Tricore/Msc/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Mtu/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Pms/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Port/Io \
0_Src/BaseSw/iLLD/TC37A/Tricore/Port/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Psi5/Psi5 \
0_Src/BaseSw/iLLD/TC37A/Tricore/Psi5/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Psi5s/Psi5s \
0_Src/BaseSw/iLLD/TC37A/Tricore/Psi5s/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Qspi/SpiMaster \
0_Src/BaseSw/iLLD/TC37A/Tricore/Qspi/SpiSlave \
0_Src/BaseSw/iLLD/TC37A/Tricore/Qspi/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Scu/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Sent/Sent \
0_Src/BaseSw/iLLD/TC37A/Tricore/Sent/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Smu/Smu \
0_Src/BaseSw/iLLD/TC37A/Tricore/Smu/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Src/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Stm/Std \
0_Src/BaseSw/iLLD/TC37A/Tricore/Stm/Timer \
0_Src/BaseSw/iLLD/TC37A/Tricore/_Impl \
0_Src/BaseSw/iLLD/TC37A/Tricore/_Lib/DataHandling \
0_Src/BaseSw/iLLD/TC37A/Tricore/_Lib/InternalMux \
0_Src/BaseSw/iLLD/TC37A/Tricore/_PinMap \

